name = "jryanrussow-site"
# main = "functions/_middleware.js"  ← DELETE OR COMMENT THIS LINE
compatibility_date = "2026-03-20"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"