name = "jryanrussow-site"
main = "functions/_middleware.js"
compatibility_date = "2026-03-20"
compatibility_flags = ["nodejs_compat"]

[build]
format = "esm"

[assets]
directory = "."
binding = "ASSETS"